services:
  php:
    build: .
    volumes:
      - ./public:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "8181:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php